spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:}
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:}
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: ${spring.application.name}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest