version: '2.4'
services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: cloudmore_mysql
        volumes:
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        command: --long_query_time=100 --slow_query_log='OFF' --slow_query_log_file='/var/lib/mysql/slow.log' --character_set_server=utf8 --collation-server=utf8_bin --default-time-zone='UTC'
    swagger-ui:
        image: swaggerapi/swagger-ui
        restart: always
        container_name: cloudmore_swagger
        environment:
            BASE_URL: /swagger
    kafka:
        image: wurstmeister/kafka:latest
        restart: always
        container_name: cloudmore_kafka
        hostname: cloudmore_kafka
        environment:
            KAFKA_ZOOKEEPER_CONNECT: cloudmore_zookeeper:2181
            HOSTNAME_COMMAND: "hostname -i"
            KAFKA_HEAP_OPTS: -Xmx1G
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        mem_limit: 1G
        mem_reservation: 512M
        cpus: 1
        depends_on:
            - zookeeper
    zookeeper:
        image: wurstmeister/zookeeper
        restart: always
        container_name: cloudmore_zookeeper
        hostname: cloudmore_zookeeper
        mem_limit: 512M
        mem_reservation: 128M
        cpus: 0.5
        logging:
            options:
                max-size: "10m"
                max-file: "3"
    kafka_web:
        image: obsidiandynamics/kafdrop
        restart: always
        container_name: cloudmore_kafka_web
        hostname: cloudmore_kafka_web
        environment:
            KAFKA_BROKERCONNECT: cloudmore_kafka:9092
        depends_on:
            - kafka
